#!/usr/bin/env python3
"""
ClarifEye — Traffic Light Model Training & Export Script
=========================================================

RUNS ON  : development machine with a CUDA GPU (NOT on the Raspberry Pi).
PURPOSE  : Fine-tune YOLOv8n on a 3-class traffic light dataset, then export
           the best weights to TFLite INT8 for deployment on the Pi.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 0 — OBTAIN A DATASET
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Recommended public datasets:

1. LISA Traffic Light Dataset  (University of California San Diego)
   URL  : http://cvrr.ucsd.edu/LISA/lisa-traffic-light-dataset.html
   Size : ~43 000 annotated frames from US roads.
   Notes: Labels use ["go", "stop", "goLeft", "goForward", "warning"] — remap:
            stop / stopLeft  → class 0  (red)
            warning          → class 1  (yellow)
            go / goForward / goLeft → class 2  (green)

2. S2TLD — Small-scale Traffic Light Dataset  (SJTU Think Lab)
   URL  : https://github.com/Thinklab-SJTU/S2TLD
   Size : ~5 000 images, 5 classes.
   Notes: Merge:
            red   → class 0
            yellow → class 1
            green  → class 2
            off / unknown → discard

3. COCO 2017 traffic-light subset
   Filter the COCO images that contain "traffic_light" annotations, then
   re-annotate per-state using Roboflow or LabelImg — COCO only marks the
   bounding box, not the current state.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 1 — ORGANISE INTO YOLO FORMAT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Required directory layout (set DATASET_ROOT below):

    <DATASET_ROOT>/
    ├── images/
    │   ├── train/     ← ~80 % of your images
    │   ├── val/       ← ~10 %
    │   └── test/      ← ~10 %
    └── labels/
        ├── train/     ← one .txt per image, same file-stem
        ├── val/
        └── test/

Each label file contains one row per bounding box:

    <class_id> <cx> <cy> <w> <h>

All five values are normalised 0–1 relative to the image width/height.
class_id:  0 = red  |  1 = yellow  |  2 = green

Example label line for a red light:
    0 0.512 0.340 0.045 0.110

Quick 80/10/10 split from a flat directory of images + labels:

    python - <<'EOF'
    import os, random, shutil, pathlib
    src_imgs   = pathlib.Path("all_images")
    src_labels = pathlib.Path("all_labels")
    files = [f.stem for f in src_imgs.glob("*.jpg")]
    random.shuffle(files)
    n = len(files)
    splits = {
        "train": files[:int(n * 0.8)],
        "val":   files[int(n * 0.8):int(n * 0.9)],
        "test":  files[int(n * 0.9):],
    }
    for split, stems in splits.items():
        for stem in stems:
            for ext, src in [(".jpg", src_imgs), (".txt", src_labels)]:
                dst = pathlib.Path(f"dataset/{'images' if ext=='.jpg' else 'labels'}/{split}")
                dst.mkdir(parents=True, exist_ok=True)
                shutil.copy(src / (stem + ext), dst / (stem + ext))
    EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 2 — EDIT CONFIGURATION BELOW, THEN RUN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    python scripts/train_traffic_light.py

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STEP 3 — DEPLOY TO THE RASPBERRY PI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The script prints the exact scp command after a successful export.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
dataset.yaml TEMPLATE (auto-generated by this script at DATASET_ROOT):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    path: /absolute/path/to/dataset
    train: images/train
    val:   images/val
    test:  images/test
    nc: 3
    names: ['red', 'yellow', 'green']
"""

import logging
import sys
from pathlib import Path

# ─── USER CONFIGURATION ───────────────────────────────────────────────────────

# Absolute path to the root of your YOLO-format dataset.
DATASET_ROOT: str = "/path/to/your/dataset"

# Training output root.  Each run creates a subdirectory named EXPERIMENT_NAME.
PROJECT_DIR: str = "runs/train"

# Experiment label — also used as the destination subdirectory name.
EXPERIMENT_NAME: str = "traffic_light_v1"

# GPU device index.  Set to "cpu" for CPU-only environments.
DEVICE: int | str = 0

# ─── TRAINING HYPER-PARAMETERS ───────────────────────────────────────────────

EPOCHS: int = 100
IMAGE_SIZE: int = 640
BATCH_SIZE: int = 16
PATIENCE: int = 15           # Early-stopping: epochs without mAP improvement.
OPTIMIZER: str = "AdamW"
LEARNING_RATE: float = 0.001
AUGMENT: bool = True

# ─── MODEL CLASSES — must match config.TRAFFIC_LIGHT_CLASSES ─────────────────

CLASS_NAMES: list[str] = ["red", "yellow", "green"]
NUM_CLASSES: int = len(CLASS_NAMES)

# ─── END USER CONFIGURATION ───────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("clarifeye.train")


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _validate_dataset(root: Path) -> None:
    """
    Abort with a clear message if the dataset directory is missing or
    does not contain the expected subdirectory structure.

    Args:
        root: Resolved absolute path to ``DATASET_ROOT``.
    """
    if not root.exists():
        logger.error(
            "DATASET_ROOT does not exist: %s\n"
            "Edit the DATASET_ROOT variable at the top of this script.",
            root,
        )
        sys.exit(1)

    required: list[Path] = [
        root / "images" / "train",
        root / "images" / "val",
        root / "labels" / "train",
        root / "labels" / "val",
    ]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        logger.error(
            "Missing required subdirectories in DATASET_ROOT:\n  %s\n"
            "See the header of this script for the expected layout.",
            "\n  ".join(missing),
        )
        sys.exit(1)


def _write_dataset_yaml(root: Path) -> Path:
    """
    Write a ``dataset.yaml`` conforming to the Ultralytics YOLO format
    into the dataset root directory.

    Args:
        root: Resolved absolute path to ``DATASET_ROOT``.

    Returns:
        Path to the written YAML file.
    """
    yaml_path = root / "dataset.yaml"
    content = (
        f"path: {root}\n"
        f"train: images/train\n"
        f"val:   images/val\n"
        f"test:  images/test\n"
        f"nc: {NUM_CLASSES}\n"
        f"names: {CLASS_NAMES}\n"
    )
    yaml_path.write_text(content, encoding="utf-8")
    logger.info("dataset.yaml written: %s", yaml_path)
    return yaml_path


def _find_tflite_export(run_dir: Path) -> Path | None:
    """
    Locate the exported ``.tflite`` file under *run_dir*.

    Prefers files whose name contains ``"int8"``; falls back to the first
    ``.tflite`` file found if none matches.

    Args:
        run_dir: Root of the training output directory.

    Returns:
        Path to the ``.tflite`` file, or ``None`` if none was found.
    """
    candidates = list(run_dir.rglob("*.tflite"))
    if not candidates:
        return None
    for candidate in candidates:
        if "int8" in candidate.name.lower():
            return candidate
    return candidates[0]


def _print_deploy_instructions(tflite_path: Path) -> None:
    """
    Print copy / verification instructions for deploying the model to the Pi.

    Args:
        tflite_path: Local path to the exported ``.tflite`` file.
    """
    pi_dest = (
        "pi@raspberrypi.local:~/clarifeye/models/traffic_light_yolov8n.tflite"
    )
    size_kb = tflite_path.stat().st_size / 1024

    border = "=" * 72
    print(f"\n{border}")
    print("  EXPORT COMPLETE")
    print(border)
    print(f"  Model : {tflite_path}")
    print(f"  Size  : {size_kb:.1f} KB")
    print()
    print("  1. Copy to Raspberry Pi:")
    print(f"       scp {tflite_path} {pi_dest}")
    print()
    print("  2. On the Pi, verify tflite_runtime works:")
    print(
        "       python -c \""
        "from tflite_runtime.interpreter import Interpreter; "
        "print('tflite_runtime OK')\""
    )
    print()
    print("  3. Test the detector:")
    print(
        "       python -c \""
        "from clarifeye.ai.traffic_light_detector import TrafficLightDetector; "
        "d = TrafficLightDetector(); "
        "print('model loaded:', d._available)\""
    )
    print(border + "\n")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    """
    Entry point: validate dataset, train YOLOv8n, export to TFLite INT8.
    """
    try:
        from ultralytics import YOLO  # type: ignore[import-untyped]
    except ImportError:
        logger.error(
            "ultralytics is not installed. Run: pip install ultralytics"
        )
        sys.exit(1)

    dataset_root = Path(DATASET_ROOT).resolve()
    _validate_dataset(dataset_root)
    yaml_path = _write_dataset_yaml(dataset_root)

    logger.info("Loading YOLOv8n base weights (yolov8n.pt) …")
    model = YOLO("yolov8n.pt")

    logger.info(
        "Training  epochs=%d  imgsz=%d  batch=%d  device=%s  patience=%d",
        EPOCHS,
        IMAGE_SIZE,
        BATCH_SIZE,
        DEVICE,
        PATIENCE,
    )
    results = model.train(
        data=str(yaml_path),
        epochs=EPOCHS,
        imgsz=IMAGE_SIZE,
        batch=BATCH_SIZE,
        device=DEVICE,
        patience=PATIENCE,
        optimizer=OPTIMIZER,
        lr0=LEARNING_RATE,
        augment=AUGMENT,
        project=PROJECT_DIR,
        name=EXPERIMENT_NAME,
    )

    run_dir = Path(results.save_dir)
    logger.info("Training complete.  Run directory: %s", run_dir)

    best_weights = run_dir / "weights" / "best.pt"
    if not best_weights.exists():
        logger.error(
            "best.pt not found at %s — check for training errors above.",
            best_weights,
        )
        sys.exit(1)

    logger.info("Exporting best weights to TFLite INT8 …")
    export_model = YOLO(str(best_weights))
    export_model.export(
        format="tflite",
        int8=True,
        data=str(yaml_path),
        imgsz=IMAGE_SIZE,
    )

    tflite_path = _find_tflite_export(run_dir)
    if tflite_path is None:
        logger.error(
            "Could not locate a .tflite file under %s.\n"
            "Check the ultralytics export output above for errors.",
            run_dir,
        )
        sys.exit(1)

    logger.info("TFLite INT8 model: %s", tflite_path)
    _print_deploy_instructions(tflite_path)


if __name__ == "__main__":
    main()
